# Generated by Django 3.0.6 on 2020-05-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_keeper_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='humidy',
            new_name='humidity',
        ),
    ]
