# Generated by Django 3.0.4 on 2020-05-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_keeper_api', '0002_auto_20200522_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='message',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
